# -*- coding: utf-8 -*-
"""Take Home Test_Chatharina_Data Analyst.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kna4iFyZrEzw23tXU9t_o9vrwKuLjMIB
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import streamlit as st

file_id = '1V1wjn7L8D2yjk2cMIwX6vJIRUC-gRDC-'
download_url = f'https://drive.google.com/uc?export=download&id={file_id}'

df = pd.read_csv(download_url)

"""Data Understanding"""

st.dataframe(df.head())

st.dataframe(df.describe().T)

st.write("Shape:", df.shape)

import io
buf = io.StringIO()
df.info(buf=buf)
st.text(buf.getvalue())

"""Cek Duplikat"""

df.duplicated().sum()

"""Cek Missing Value"""

df.isnull().sum()

missing_percentage = df.isnull().sum()/df.shape[0]*100
missing_percentage.sort_values(ascending=False)

"""Cek Outlier kolom numerik"""

numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:
  Q1 = df[col].quantile(0.25)
  Q3 = df[col].quantile(0.75)
  IQR = Q3 - Q1
  lower_bound = Q1 - 1.5 * IQR
  upper_bound = Q3 + 1.5 * IQR

  outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
  outlier_count = len(outliers)
  outlier_percentage = (outlier_count / len(df)) * 100
  st.write(f"{col}: {outlier_count} outliers ({outlier_percentage:.2f}%)")

"""Feature Engineering"""

df['Data'] = pd.to_datetime(df['Data'], errors='coerce')
if df['Data'].isna().any():
    st.warning("Ada baris gagal parse tanggal di 'Data'. Baris tsb akan di-drop.")
    df = df.dropna(subset=['Data'])
df = df.sort_values('Data')

# Fitur kalender"""

df['Tanggal'] = df['Data'].dt.date
df['Tahun'] = df['Data'].dt.year
df['Bulan'] = df['Data'].dt.month
df['Quarter'] = df['Data'].dt.quarter
df['Weekday'] = df['Data'].dt.dayofweek
df['IsWeekend'] = df['Weekday'] >= 5
df['Periode'] = df['Data'].dt.to_period('M')
df['Periode_ts']= df['Periode'].dt.to_timestamp()

# Standarkan ke level bulanan"""

monthly = (
  df.groupby(['Periode','Loja_ID','Tipo de Custo'], as_index=False)['Valor Mensal'].sum()
    .rename(columns={'Valor Mensal':'Valor_Mensal'})
)
monthly['Periode_ts'] = monthly['Periode'].dt.to_timestamp()

# Fitur tren/growth/seasonality per toko & kategori"""

monthly = monthly.sort_values(['Loja_ID','Tipo de Custo','Periode'])
grp = monthly.groupby(['Loja_ID','Tipo de Custo'], group_keys=False)

# Lag & rolling
monthly['Lag_1']   = grp['Valor_Mensal'].shift(1)
monthly['Lag_12']  = grp['Valor_Mensal'].shift(12)
monthly['RollMean_3']  = grp['Valor_Mensal'].rolling(3, min_periods=1).mean().reset_index(level=[0,1], drop=True)
monthly['RollMean_6']  = grp['Valor_Mensal'].rolling(6, min_periods=1).mean().reset_index(level=[0,1], drop=True)

monthly['MoM_grp'] = grp['Valor_Mensal'].pct_change(1).replace([np.inf,-np.inf], np.nan)
monthly['QoQ_grp'] = grp['Valor_Mensal'].pct_change(3).replace([np.inf,-np.inf], np.nan)
monthly['MA3_grp'] = grp['Valor_Mensal'].rolling(3, min_periods=1).mean().reset_index(level=[0,1], drop=True)
monthly['MA6_grp'] = grp['Valor_Mensal'].rolling(6, min_periods=1).mean().reset_index(level=[0,1], drop=True)
monthly['YoY_grp'] = grp['Valor_Mensal'].pct_change(12).replace([np.inf,-np.inf], np.nan)

m_total = (monthly.groupby('Periode', as_index=False)['Valor_Mensal']
  .sum().sort_values('Periode')
  .rename(columns={'Valor_Mensal':'Valor_Total'}))
m_total['MA3'] = m_total['Valor_Total'].rolling(3, min_periods=1).mean()
m_total['MA6'] = m_total['Valor_Total'].rolling(6, min_periods=1).mean()
m_total['YoY'] = m_total['Valor_Total'].pct_change(12).replace([np.inf,-np.inf], np.nan)

cat = (monthly.groupby(['Periode','Tipo de Custo'], as_index=False)['Valor_Mensal']
  .sum().sort_values(['Tipo de Custo','Periode'])
  .rename(columns={'Valor_Mensal':'Valor_Kategori'}))
cat['YoY'] = cat.groupby('Tipo de Custo')['Valor_Kategori'].pct_change(12).replace([np.inf,-np.inf], np.nan)
cat['QoQ'] = cat.groupby('Tipo de Custo')['Valor_Kategori'].pct_change(3).replace([np.inf,-np.inf], np.nan)

store = (monthly.groupby(['Periode','Loja_ID'], as_index=False)['Valor_Mensal']
  .sum().sort_values(['Loja_ID','Periode'])
  .rename(columns={'Valor_Mensal':'Valor_Toko'}))
store['QoQ'] = store.groupby('Loja_ID')['Valor_Toko'].pct_change(3).replace([np.inf,-np.inf], np.nan)

# pastikan punya timestamp & period kuartal
store['Periode_ts'] = store['Periode'].dt.to_timestamp()
store['Q'] = store['Periode_ts'].dt.to_period('Q')

# agregasi ke level kuartal per toko (kalau bulan ada yang hilang, dijumlahkan yang ada)
store_q = (store.groupby(['Loja_ID', 'Q'], as_index=False)['Valor_Toko']
  .sum())

# bikin grid lengkap semua Loja_ID × semua kuartal dalam rentang data
all_loja = store_q['Loja_ID'].dropna().unique()
q_min, q_max = store_q['Q'].min(), store_q['Q'].max()
all_q = pd.period_range(q_min, q_max, freq='Q')
grid = pd.MultiIndex.from_product([all_loja, all_q], names=['Loja_ID', 'Q'])

# reindex ke grid lengkap, isi yang kosong dengan 0 (bukan NaN)
store_q = (store_q.set_index(['Loja_ID','Q'])
  .reindex(grid, fill_value=0)
  .reset_index())

# materialisasikan kolom yang Tableau butuh tanpa parsing
store_q['Year']    = store_q['Q'].dt.year
store_q['Quarter'] = store_q['Q'].dt.quarter
store_q = store_q.rename(columns={'Valor_Toko':'Valor_Toko_Q'})

cat['Periode_ts'] = cat['Periode'].dt.to_timestamp()
cat['Q'] = cat['Periode_ts'].dt.to_period('Q')

cat_q = (cat.groupby(['Tipo de Custo', 'Q'], as_index=False)['Valor_Kategori']
  .sum())

all_cat = cat_q['Tipo de Custo'].dropna().unique()
q_min_c, q_max_c = cat_q['Q'].min(), cat_q['Q'].max()
all_q_c = pd.period_range(q_min_c, q_max_c, freq='Q')
grid_c = pd.MultiIndex.from_product([all_cat, all_q_c], names=['Kategori', 'Q'])

cat_q = (cat_q.rename(columns={'Tipo de Custo':'Kategori'})
  .set_index(['Kategori','Q'])
  .reindex(grid_c, fill_value=0)
  .reset_index())

cat_q['Year']    = cat_q['Q'].dt.year
cat_q['Quarter'] = cat_q['Q'].dt.quarter
cat_q = cat_q.rename(columns={'Valor_Kategori':'Valor_Kategori_Q'})

st.write({
  'YoY_total_notna': int(m_total['YoY'].notna().sum()),
  'YoY_cat_any': int(cat.groupby('Tipo de Custo')['YoY'].apply(lambda s: s.notna().any()).sum()),
  'QoQ_store_notna': int(store['QoQ'].notna().sum())
})

# Z-score untuk deteksi spike relatif historinya
monthly['ZScore'] = grp['Valor_Mensal'].transform(lambda s: (s - s.mean())/s.std(ddof=0))

# per-toko per-kuartal
s3 = (store[['Periode','Loja_ID','Valor_Toko','QoQ']].copy()
  .assign(Periode_ts=lambda d: d['Periode'].dt.to_timestamp(),
    Year=lambda d: d['Periode'].dt.year,
    Quarter=lambda d: d['Periode'].dt.quarter)
  .melt(id_vars=['Periode','Periode_ts','Year','Quarter','Loja_ID'],
    value_vars=['Valor_Toko','QoQ'],
    var_name='metric', value_name='value'))
s3['section'] = 'series_toko'
s3['Periode'] = s3['Periode'].astype(str)
s3['Periode_ts'] = s3['Periode_ts'].dt.strftime('%Y-%m-%d')
for c in ['Loja_ID','metric','section']: s3[c] = s3[c].fillna('')
s3['value'] = pd.to_numeric(s3['value'], errors='coerce').fillna(0.0)
assert s3.isna().sum().sum() == 0
s3.to_csv('operational_costs_export_onefile.csv', index=False)

"""Flag kebijakan/kualitas data waktu"""

today = pd.Timestamp.today().normalize()
monthly['Is_Future'] = monthly['Periode_ts'] > today
monthly['Is_Q_End'] = monthly['Periode_ts'].dt.is_quarter_end
monthly['Is_Y_End'] = monthly['Periode_ts'].dt.is_year_end

"""Sanity Check"""

# Pastikan nama kolom growth di level grup beda agar tidak ketuker
monthly = monthly.rename(columns={'MoM': 'MoM_grp', 'YoY': 'YoY_grp'})

# Sanity check level GRUP (Loja × Kategori × Bulan) ----
dup_bucket = (monthly.groupby(['Periode','Loja_ID','Tipo de Custo']).size().gt(1).sum())
future_rows = monthly['Is_Future'].sum()
nan_grp = monthly[['MoM_grp','YoY_grp']].isna().sum().to_dict()

# KPI level AGREGAT
# total
m_total = (monthly.groupby('Periode', as_index=False)['Valor_Mensal']
  .sum().sort_values('Periode')
  .rename(columns={'Valor_Mensal':'Valor_Total'}))
m_total['YoY'] = m_total['Valor_Total'].pct_change(12).replace([np.inf,-np.inf], np.nan)

# kategori
cat = (monthly.groupby(['Periode','Tipo de Custo'], as_index=False)['Valor_Mensal']
  .sum().sort_values(['Tipo de Custo','Periode'])
  .rename(columns={'Valor_Mensal':'Valor_Kategori'}))
cat['YoY'] = cat.groupby('Tipo de Custo')['Valor_Kategori'].pct_change(12).replace([np.inf,-np.inf], np.nan)

# toko
store = (monthly.groupby(['Periode','Loja_ID'], as_index=False)['Valor_Mensal']
  .sum().sort_values(['Loja_ID','Periode'])
  .rename(columns={'Valor_Mensal':'Valor_Toko'}))
store['QoQ'] = store.groupby('Loja_ID')['Valor_Toko'].pct_change(3).replace([np.inf,-np.inf], np.nan)

# lengkapi dimensi waktu & jaga Loja_ID tetap ada
store['Periode_ts'] = store['Periode'].dt.to_timestamp()
store['Year'] = store['Periode_ts'].dt.year
store['Quarter'] = store['Periode_ts'].dt.quarter
store['Loja_ID'] = store['Loja_ID'].astype(str)

st.write({
  # level grup (akan tetap tinggi)
  'dup_bucket>1': int(dup_bucket),
  'rows_future_date': int(future_rows),
  'NaN_MoM_grp': int(nan_grp['MoM_grp']),
  'NaN_YoY_grp': int(nan_grp['YoY_grp']),
  # level agregat (yang kamu butuhkan untuk KPI)
  'YoY_total_notna': int(m_total['YoY'].notna().sum()),
  'YoY_cat_any': int(cat.groupby('Tipo de Custo')['YoY'].apply(lambda s: s.notna().any()).sum()),
  'QoQ_store_notna': int(store['QoQ'].notna().sum()),
})

"""Ringkasan Sanity Check:
- Duplikasi per (Bulan×Toko×Kategori): 0 artinya data konsisten, tidak ada double counting.
- Tanggal masa depan: 0 jadi tidak ada tanggal aneh/invalid.
- MoM per-grup NaN: 20 baris, ini hanya baris bulan pertama tiap grup (wajar tidak punya pembanding).
- YoY per-grup NaN: 99 baris, tapi bukan masalah kualitas data: tiap (Toko×Kategori) belum punya ≥13 bulan histori, jadi YoY memang tidak terdefinisi di level ini.
- YoY total tersedia: 59 bulan jadi di level total perusahaan histori cukup, jadi KPI YoY tetap bisa dihitung.
- YoY per kategori tersedia pada 4 kategori jadi sisanya kita pakai QoQ sebagai alternatif.
- QoQ per toko valid: 77 titik dimana cukup untuk insight operasional per toko.

KPI Kartu
"""

if 'Valor_Total' not in m_total.columns:
  m_total = (monthly.groupby('Periode', as_index=False)['Valor_Mensal']
    .sum().sort_values('Periode')
    .rename(columns={'Valor_Mensal':'Valor_Total'}))
else:
  m_total = m_total.sort_values('Periode').reset_index(drop=True)

if 'YoY' not in m_total.columns:
  m_total['YoY'] = m_total['Valor_Total'].pct_change(12).replace([np.inf, -np.inf], np.nan)
if 'MA3' not in m_total.columns:
  m_total['MA3'] = m_total['Valor_Total'].rolling(3, min_periods=1).mean()

last = m_total.iloc[-1]
prev = m_total.iloc[-2] if len(m_total) > 1 else None

def pct(a, b):
  if (b is None) or pd.isna(b) or b == 0:
    return None
  return float((a - b) / b)

st.write(m_total.columns.tolist())

kpi = {
  "Total kumulatif": float(m_total['Valor_Total'].sum()),
  "Rata2/bulan": float(m_total['Valor_Total'].mean()),
  "Bulan terakhir": float(last['Valor_Total']),
  "MoM (total)": None if prev is None else pct(float(last['Valor_Total']), float(prev['Valor_Total'])),
  "YoY (total)": None if pd.isna(last['YoY']) else float(last['YoY']),
  "Run-rate 12m (MA3*12)": float(m_total['MA3'].iloc[-1] * 12),
}
kpi

"""Visualisasi

Tren total + MA3/MA6
"""

m_total = m_total.sort_values('Periode').reset_index(drop=True)

if 'MA3' not in m_total.columns:
  m_total['MA3'] = m_total['Valor_Total'].rolling(3, min_periods=1).mean()
if 'MA6' not in m_total.columns:
  m_total['MA6'] = m_total['Valor_Total'].rolling(6, min_periods=1).mean()

if 'Periode_ts' not in m_total.columns:
  m_total['Periode_ts'] = m_total['Periode'].dt.to_timestamp()

fig, ax = plt.subplots(figsize=(9,4))
ax.plot(m_total['Periode_ts'], m_total['Valor_Total'], label='Total')
ax.plot(m_total['Periode_ts'], m_total['MA3'], label='MA3')
ax.plot(m_total['Periode_ts'], m_total['MA6'], label='MA6')
ax.set_title('Total Biaya Bulanan + MA3/MA6')
ax.set_xlabel('Periode')
ax.set_ylabel('Biaya')
ax.legend()
st.pyplot(fig)

"""YoY total (bar)"""

from matplotlib.ticker import PercentFormatter

q = (m_total.assign(Periode_ts=m_total['Periode'].dt.to_timestamp())
     .set_index('Periode_ts').resample('Q')['Valor_Total'].sum()
     .reset_index().rename(columns={'Valor_Total':'Valor_Q'}))
q['YoY'] = q['Valor_Q'].pct_change(4)

qs = q[q['YoY'].notna()].tail(8).copy()
qs['Qlabel'] = pd.PeriodIndex(qs['Periode_ts'], freq='Q').astype(str)
x = np.arange(len(qs))

fig, ax = plt.subplots(figsize=(9,4))
ax.bar(x, qs['YoY'].clip(-1, 1))
ax.yaxis.set_major_formatter(PercentFormatter(1.0))
ax.set_xticks(x)
ax.set_xticklabels(qs['Qlabel'], rotation=0)
ax.set_ylim(-1.1, 1.1)
ax.axhline(0, linewidth=1)
ax.set_title('YoY Total per Kuartal (Last 8 Quarters)')
ax.set_xlabel('Kuartal')
ax.set_ylabel('YoY')
st.pyplot(fig)

"""Komposisi kategori per bulan (100% stacked area)"""

mix = (monthly.pivot_table(index='Periode', columns='Tipo de Custo', 
                           values='Valor_Mensal', aggfunc='sum')
       .fillna(0).sort_index())
share = mix.div(mix.sum(1), axis=0)

ax2 = share.plot(kind='area', figsize=(10,4))
ax2.set_title('Komposisi % Biaya per Kategori')
ax2.set_ylabel('Share')
fig2 = ax2.get_figure()
st.pyplot(fig2)

"""YoY atau QoQ per kategori (pilih otomatis)"""

recent = cat.copy()
metric = 'YoY' if recent['YoY'].notna().any() else 'QoQ'
last6 = (recent.dropna(subset=[metric])
         .sort_values('Periode').groupby('Tipo de Custo').tail(1)
         .sort_values(metric))

fig, ax = plt.subplots(figsize=(8,4))
ax.barh(last6['Tipo de Custo'], last6[metric])
ax.axvline(0, linewidth=1)
ax.set_title(f'{metric} Terakhir per Kategori')
st.pyplot(fig)

"""Ranking toko (kumulatif)"""

rank_toko = (store.groupby('Loja_ID', as_index=False)['Valor_Toko']
             .sum().sort_values('Valor_Toko', ascending=True))
fig, ax = plt.subplots(figsize=(8,5))
ax.barh(rank_toko['Loja_ID'].astype(str), rank_toko['Valor_Toko'])
ax.set_title('Total Biaya per Toko')
st.pyplot(fig)

"""Tabel ringkas untuk narasi"""

# Top cost drivers (global)
top_global = (monthly.groupby('Tipo de Custo', as_index=False)['Valor_Mensal']
  .sum().sort_values('Valor_Mensal', ascending=False))

# Perubahan komposisi (bulan terakhir vs 6 bulan sebelumnya)
lastP = mix.index.max()
prev6 = mix.index.sort_values()[-6:]
share_change = pd.DataFrame({
  'share_last': (mix.loc[lastP] / mix.loc[lastP].sum()),
  'share_prev6': (mix.loc[prev6].sum() / mix.loc[prev6].sum().sum())
})
share_change['delta_pp'] = (share_change['share_last'] - share_change['share_prev6'])*100
share_change = share_change.sort_values('delta_pp', ascending=False)

# Toko paling boros & paling volatile
toko_stats = (store.groupby('Loja_ID')['Valor_Toko']
  .agg(total='sum', mean='mean', std='std'))
toko_stats['cv'] = toko_stats['std']/toko_stats['mean']
toko_rank = toko_stats.sort_values('total', ascending=False)
toko_vol  = toko_stats.sort_values('cv', ascending=False)

top_global.head(5), share_change.head(5), toko_rank.head(5), toko_vol.head(5)

"""# Extract Artefact"""

rows = []

# 1) KPI
rows.append(pd.DataFrame([kpi]).assign(section='kpi_total'))

# 2) Series total
mt = m_total.copy()
mt['Periode'] = mt['Periode'].astype(str)
rows.append(mt.assign(section='series_total'))

# 3) Series kategori
ct = cat.copy()
ct['Periode'] = ct['Periode'].astype(str)
rows.append(ct.rename(columns={'Tipo de Custo':'Kategori'}).assign(section='series_kategori'))

# 4) Series toko
rows.append(
  store_q[['Loja_ID','Year','Quarter','Valor_Toko_Q']].assign(section='series_toko')
)
rows.append(
  cat_q[['Kategori','Year','Quarter','Valor_Kategori_Q']].assign(section='series_kategori_q')
)

# 5) Top drivers
rows.append(top_global.rename(columns={'Tipo de Custo':'Kategori'}).assign(section='top_cost_drivers'))

# 6) Perubahan komposisi
sc = share_change.copy()
sc.index.name = 'Kategori'
rows.append(sc.reset_index().assign(section='perubahan_komposisi'))

# 7) Ranking & volatilitas toko
rows.append(toko_rank.reset_index().rename(columns={'index':'Loja_ID'}).assign(section='toko_terboros'))
rows.append(toko_vol.reset_index().rename(columns={'index':'Loja_ID'}).assign(section='toko_tervolatil'))

def to_long(df, id_cols, value_cols, section_name, rename_map=None):
  t = df.copy()
  if rename_map:
    t = t.rename(columns=rename_map)
  # hanya ambil kolom yang ada supaya aman
  cols_exist = [c for c in id_cols + value_cols if c in t.columns]
  t = t[cols_exist]
  # melt ke metric–value
  t = t.melt(id_vars=[c for c in id_cols if c in t.columns],
    value_vars=[c for c in value_cols if c in t.columns],
    var_name='metric', value_name='value')
  # buang baris yang value-nya NaN (mis. YoY awal periode)
  t = t.dropna(subset=['value'])
  t['section'] = section_name
  return t

# 1) KPI (sudah single row) -> long
kpi_long = (pd.Series(kpi).reset_index()
  .rename(columns={'index':'metric', 0:'value'})
  .assign(section='kpi_total',
    Periode='', Periode_ts=pd.NaT, Year=0, Quarter=0,
    Loja_ID='', Kategori=''))

# 2) Total (agregat)
m_total['Periode_ts'] = m_total['Periode'].dt.to_timestamp()
total_long = to_long(
  m_total,
  id_cols=['Periode','Periode_ts'],
  value_cols=['Valor_Total','MA3','MA6','YoY'],
  section_name='series_total'
)

# 3) Kategori
cat['Periode_ts'] = cat['Periode'].dt.to_timestamp()
cat_long = to_long(
  cat.rename(columns={'Tipo de Custo':'Kategori'}),
  id_cols=['Periode','Periode_ts','Kategori'],
  value_cols=['Valor_Kategori','YoY','QoQ'],
  section_name='series_kategori'
)

# 4) Toko
store_long = to_long(
  store,
  id_cols=['Periode','Periode_ts','Year','Quarter','Loja_ID'],
  value_cols=['Valor_Toko','QoQ'],
  section_name='series_toko'
)

# 5) Top drivers (global)
top_global_long = (top_global.rename(columns={'Tipo de Custo':'Kategori','Valor_Mensal':'value'})
  .assign(section='top_cost_drivers',
    metric='total',
    Periode='', Periode_ts=pd.NaT, Year=0, Quarter=0,
    Loja_ID=''))

# 6) Perubahan komposisi
sc = share_change.copy().reset_index()

# kalau hasil reset_index bukan 'Kategori', rename kolom pertama jadi 'Kategori'
if 'Kategori' not in sc.columns:
  sc = sc.rename(columns={sc.columns[0]: 'Kategori'})

share_change_long = (
  sc.melt(id_vars=['Kategori'], var_name='metric', value_name='value')
    .dropna(subset=['value'])  # jaga tetap tanpa NaN
    .assign(section='perubahan_komposisi',
      Periode='', Periode_ts=pd.NaT, Year=0, Quarter=0, Loja_ID='')
)

# 7) Ranking & volatilitas toko
toko_rank_long = (toko_rank.reset_index().rename(columns={'index':'Loja_ID'})
  .melt(id_vars=['Loja_ID'], var_name='metric', value_name='value')
  .assign(section='toko_terboros',
    Periode='', Periode_ts=pd.NaT, Year=0, Quarter=0,
    Kategori=''))

toko_vol_long = (toko_vol.reset_index().rename(columns={'index':'Loja_ID'})
  .melt(id_vars=['Loja_ID'], var_name='metric', value_name='value')
  .assign(section='toko_tervolatil',
    Periode='', Periode_ts=pd.NaT, Year=0, Quarter=0,
    Kategori=''))

from pandas.tseries.offsets import MonthEnd

raw = df.copy() if "df" in locals() else pd.read_csv(download_url)

mm = {c.lower().strip(): c for c in raw.columns}
LJ, CAT, VAL, DT = mm['loja_id'], mm['tipo de custo'], mm['valor mensal'], mm['data']

def pct_safe(a, periods):
  shifted = a.shift(periods)
  return np.where(shifted != 0, (a - shifted) / shifted, np.nan)

r = raw[[LJ, CAT, VAL, DT]].copy()
r[DT] = pd.to_datetime(r[DT], errors='raise')
r['Per_M'] = r[DT].dt.to_period('M')

m = (r.groupby([LJ, CAT, 'Per_M'], as_index=False)[VAL]
  .sum().rename(columns={VAL:'Valor_Mensal'}))

def complete_months(g):
  idx = pd.period_range(g['Per_M'].min(), g['Per_M'].max(), freq='M')
  g = g.set_index('Per_M').reindex(idx, fill_value=0)
  g.index.name = 'Per_M'
  return g.reset_index()

m = (m.sort_values([LJ, CAT, 'Per_M'])
  .reset_index(drop=True))

if 'Per_M' not in m.columns:
  m['Per_M'] = pd.PeriodIndex(pd.to_datetime(m['Periode_ts']).dt.to_period('M'), freq='M')
elif not pd.api.types.is_period_dtype(m['Per_M']):
  m['Per_M'] = pd.PeriodIndex(m['Per_M'], freq='M')

grp = m.groupby([LJ, CAT], sort=False, group_keys=False)

m['MA3'] = grp['Valor_Mensal'].transform(lambda s: s.rolling(3, min_periods=1).mean())
m['MA6'] = grp['Valor_Mensal'].transform(lambda s: s.rolling(6, min_periods=1).mean())
m['MoM'] = grp['Valor_Mensal'].transform(lambda s: s.pct_change(1))
m['YoY'] = grp['Valor_Mensal'].transform(lambda s: s.pct_change(12))

tot = (
  m[['Per_M','Valor_Mensal']].copy()
    .groupby('Per_M', as_index=False, observed=True)['Valor_Mensal'].sum()
    .rename(columns={'Valor_Mensal':'Valor_Total'})
    .sort_values('Per_M')
    .reset_index(drop=True)
)

# Ensure 'Per_M' in tot is also period[M]
if 'Per_M' not in tot.columns:
  tot['Per_M'] = pd.PeriodIndex(tot['Periode_ts'].dt.to_period('M'), freq='M')
elif not pd.api.types.is_period_dtype(tot['Per_M']):
  tot['Per_M'] = pd.PeriodIndex(tot['Per_M'], freq='M')


# metrik total
tot['MA3_total']  = tot['Valor_Total'].rolling(3, min_periods=1).mean()
tot['MA6_total']  = tot['Valor_Total'].rolling(6, min_periods=1).mean()
tot['MoM_total']  = tot['Valor_Total'].pct_change(1)
tot['YoY_total']  = tot['Valor_Total'].pct_change(12)

tot['Roll12']     = tot['Valor_Total'].rolling(12, min_periods=12).sum()
tot['YoY_Roll4Q'] = pct_safe(tot['Roll12'], 12)
tot = tot.drop(columns='Roll12')

# Add print statements
st.write("Columns of m before merge:", m.columns)
st.write("Dtypes of m before merge:", m.dtypes)
st.write("Columns of tot before merge:", tot.columns)
st.write("Dtypes of tot before merge:", tot.dtypes)
st.write("Per_M in m?", 'Per_M' in m.columns)
st.write("Per_M in tot?", 'Per_M' in tot.columns)

m = m.merge(
  tot[['Per_M','Valor_Total','MA3_total','MA6_total','MoM_total','YoY_total','YoY_Roll4Q']],
  on='Per_M', how='left', validate='m:1'
)

m['MoM'] = m['MoM'].combine_first(m['MoM_total'])
m['YoY'] = m['YoY'].combine_first(m['YoY_total'])

m['Periode'] = m['Per_M'].astype(str)
m['Periode_ts'] = m['Per_M'].dt.to_timestamp() + MonthEnd(0)
m['Year'] = m['Periode_ts'].dt.year
m['Quarter'] = m['Periode_ts'].dt.quarter

m = m.rename(columns={LJ:'Loja_ID', CAT:'Kategori'})[
  ['Loja_ID','Kategori','Periode','Periode_ts','Year','Quarter',
  'Valor_Mensal','MA3','MA6','MoM','YoY',
  'Valor_Total','MA3_total','MA6_total','YoY_total','YoY_Roll4Q']
]

num_cols = ['Valor_Mensal','MA3','MA6','MoM','YoY','Valor_Total','MA3_total','MA6_total','YoY_total','YoY_Roll4Q']
m[num_cols] = m[num_cols].astype(float).fillna(0.0)

# simpan
st.write('OK, rows:', len(m))
st.write(m.head(12))
